### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by tthtlc** [Storyyeller/enjarify#12]
I got the following errors:

>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/c/e.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/f/a.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/f/b.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/f/ba.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/f/c.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/f/f.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/a/g.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/a/h.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/a/i.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/b/h.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/b/i.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/e/l/b/j.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/a/d.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/c.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/g.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/i.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/j.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/k.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/a/n.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/d/a.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/d/a/a.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/d/a/c.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/d/c.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/b/f/ah.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/d/a/e.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/d/a/i.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/d/a/n.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()
> 
> org/a/s/d/a/s.class Traceback (most recent call last):
>   File "/mnt/sda4/project/android/enjarify/enjarify/main.py", line 38, in translate
>     class_data = writeclass.toClassFile(cls, opts)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
>     pool.write(stream)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 135, in write
>     self._writeEntry(stream, item)
>   File "/mnt/sda4/project/android/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
>     stream.u16(len(val))
> TypeError: object of type 'NoneType' has no len()

**Comment by Storyyeller** [comment]
Could you please post the apk you are trying to translate, and the way you invoked Enjarify?

**Comment by gooooooa** [comment]
> Could you please post the apk you are trying to translate, and the way you invoked Enjarify?

I have the same error. The dex file I try to translate is boot-framework_classes.dex .
[boot-framework_classes.zip](https://github.com/Storyyeller/enjarify/files/3540508/boot-framework_classes.zip)

I invoked Enjarify by the following command : 
python3 -O -m enjarify.main boot-framework_classes.dex 

my specific error :

android/gesture/GestureUtils.class Traceback (most recent call last):
File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
class_data = writeclass.toClassFile(cls, opts)
File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
pool.write(stream)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
self._writeEntry(stream, item)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

android/hardware/location/ActivityRecognitionHardware.class Traceback (most recent call last):
File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
class_data = writeclass.toClassFile(cls, opts)
File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
pool.write(stream)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
self._writeEntry(stream, item)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

**Comment by gooooooa** [comment]
> > Could you please post the apk you are trying to translate, and the way you invoked Enjarify?
> 
> I have the same error. The dex file I try to translate is boot-framework_classes.dex .
> [boot-framework_classes.zip](https://github.com/Storyyeller/enjarify/files/3540508/boot-framework_classes.zip)
> 
> I invoked Enjarify by the following command :
> python3 -O -m enjarify.main boot-framework_classes.dex

my specific error : 

android/gesture/GestureUtils.class Traceback (most recent call last):
  File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
    pool.write(stream)
  File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
    self._writeEntry(stream, item)
  File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

android/hardware/location/ActivityRecognitionHardware.class Traceback (most recent call last):
  File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
    pool.write(stream)
  File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
    self._writeEntry(stream, item)
  File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

**Comment by gooooooa** [comment]
> Could you please post the apk you are trying to translate, and the way you invoked Enjarify?

my specific error :

android/gesture/GestureUtils.class Traceback (most recent call last):
File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
class_data = writeclass.toClassFile(cls, opts)
File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
pool.write(stream)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
self._writeEntry(stream, item)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

android/hardware/location/ActivityRecognitionHardware.class Traceback (most recent call last):
File "/home/abcd/tools/enjarify/enjarify/main.py", line 38, in translate
class_data = writeclass.toClassFile(cls, opts)
File "/home/abcd/tools/enjarify/enjarify/jvm/writeclass.py", line 122, in toClassFile
pool.write(stream)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 135, in write
self._writeEntry(stream, item)
File "/home/abcd/tools/enjarify/enjarify/jvm/constantpool.py", line 104, in _writeEntry
stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

**Comment by zyv** [comment]
Same problem here, enjarify does a much better job than dex2jar, but still getting those failures on many classes... is the tool still maintained?

**Comment by Storyyeller** [comment]
Sorry, I forgot about this completely.

**Comment by Storyyeller** [comment]
I looked into this and the class in question appears to be trying to load a float as a class literal. Are you sure it's valid?

**Comment by zyv** [comment]
In my case I suspect that it might possibly be caused by Dexguard... at least it is known to inject nonsense control flow to trip up decompilers, so maybe this is another trick to break DEX parsers? However, I hope that it can be handled more gracefully on the enjarify side. The APK in question is `com.huawei.health` FWIW...

**Comment by samczsun** [comment]
FWIW I'm seeing the same issue with Spotify 8.5.33.831 (version with assets stripped [here](https://github.com/Storyyeller/enjarify/files/3934952/test.zip)). I patched enjarify to replace the invalid constants with the string "fail" and got this output (from `fog.class`):

```
L26:    iastore 
L27:    astore 5 
L29:    ldc Class fail 
L31:    astore 6 
L33:    aload 6 
L35:    aload 5 
L37:    invokestatic Method java/lang/reflect/Array newInstance (Ljava/lang/Class;[I)Ljava/lang/Object; 
L40:    checkcast [[B 
```

The bytecode seems like it's trying to do the right thing, and doesn't appear to be obfuscated either. I'm not nearly as familiar with Android as I am with Java so hopefully this is interesting enough for you to take a look

**Comment by Storyyeller** [comment]
Sorry, I keep forgetting about this. Hopefully, I'll get around to it soon.

**Comment by Storyyeller** [comment]
So what would be the correct behavior here? I don't want to just silently emit nonsense code either.

**Comment by samczsun** [comment]
So the original dalvik is nonsense, then? I thought in Spotify's case it could've been a bug in enjarify since there seemed to be no obfuscation applied beyond name mangling.

I guess it'd be ideal if the rest of the class could be translated, either by replacing the constant with something representing an invalid value or omitting the method bodies of methods that use that constant. Failing that, handling this error gracefully (log that the specific class contains an invalid cp entry?) would still be better than the current situation.

**Comment by nfllab** [comment]
This bug can be triggered with the following code:
`int[][] a = new int[2][3];`

Example APK: 
[app-debug.apk.zip](https://github.com/Storyyeller/enjarify/files/4238539/app-debug.apk.zip)

The bad thing happens when parameter of const-class is a primitive type.

**Comment by Storyyeller** [comment]
Sorry, I've been busy with other stuff and am having computer troubles.

**Comment by zeruth** [comment]
This also effects Old School Runescape:
https://www.apkmirror.com/apk/jagex-games-studio/old-school-runescape/
all versions

**Comment by Storyyeller** [comment]
I'm not sure what the technically correct thing to do here is, but I pushed a change which should help.
